// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateProject.Data;

#nullable disable

namespace RealEstateProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712132049_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateProject.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("RealEstateProject.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<string>("TargetLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("TenantId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("RealEstateProject.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingId");

                    b.HasIndex("PropId");

                    b.HasIndex("TenantId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RealEstateProject.Models.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("PropId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("RealEstateProject.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("RealEstateProject.Models.Promotion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromoId");

                    b.HasIndex("PropId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("RealEstateProject.Models.Property", b =>
                {
                    b.Property<int>("PropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropId"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RealEstateProject.Models.PropertyApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalId");

                    b.HasIndex("AdminId");

                    b.HasIndex("PropId");

                    b.ToTable("PropertyApprovals");
                });

            modelBuilder.Entity("RealEstateProject.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GiverId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("GiverId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("RealEstateProject.Models.ServicePartner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<decimal?>("CommissionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId");

                    b.ToTable("ServicePartners");
                });

            modelBuilder.Entity("RealEstateProject.Models.ServiceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("TenantId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("RealEstateProject.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlanId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("RealEstateProject.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("AllowedUnitTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasAccountManager")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasFeaturedSearch")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasMonthlyReports")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMediaCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxUnits")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("RealEstateProject.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmokingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RealEstateProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RealEstateProject.Models.Admin", b =>
                {
                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("RealEstateProject.Models.Admin", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Alert", b =>
                {
                    b.HasOne("RealEstateProject.Models.Tenant", "Tenant")
                        .WithMany("Alerts")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RealEstateProject.Models.Booking", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropId");

                    b.HasOne("RealEstateProject.Models.Tenant", "Tenant")
                        .WithMany("Bookings")
                        .HasForeignKey("TenantId");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RealEstateProject.Models.Media", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("MediaFiles")
                        .HasForeignKey("PropId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateProject.Models.Owner", b =>
                {
                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithOne("Owner")
                        .HasForeignKey("RealEstateProject.Models.Owner", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Promotion", b =>
                {
                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("Promotions")
                        .HasForeignKey("PropId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateProject.Models.Property", b =>
                {
                    b.HasOne("RealEstateProject.Models.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RealEstateProject.Models.PropertyApproval", b =>
                {
                    b.HasOne("RealEstateProject.Models.Admin", "Admin")
                        .WithMany("PropertyApprovals")
                        .HasForeignKey("AdminId");

                    b.HasOne("RealEstateProject.Models.Property", "Property")
                        .WithMany("PropertyApprovals")
                        .HasForeignKey("PropId");

                    b.Navigation("Admin");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateProject.Models.Rating", b =>
                {
                    b.HasOne("RealEstateProject.Models.User", "Giver")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("GiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RealEstateProject.Models.User", "Receiver")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Giver");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("RealEstateProject.Models.ServiceRequest", b =>
                {
                    b.HasOne("RealEstateProject.Models.ServicePartner", "ServicePartner")
                        .WithMany("Service_Requests")
                        .HasForeignKey("PartnerId");

                    b.HasOne("RealEstateProject.Models.Tenant", "Tenant")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("TenantId");

                    b.Navigation("ServicePartner");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RealEstateProject.Models.Subscription", b =>
                {
                    b.HasOne("RealEstateProject.Models.Owner", "Owner")
                        .WithMany("Subscriptions")
                        .HasForeignKey("OwnerId");

                    b.HasOne("RealEstateProject.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId");

                    b.Navigation("Owner");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("RealEstateProject.Models.Tenant", b =>
                {
                    b.HasOne("RealEstateProject.Models.User", "User")
                        .WithOne("Tenant")
                        .HasForeignKey("RealEstateProject.Models.Tenant", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateProject.Models.Admin", b =>
                {
                    b.Navigation("PropertyApprovals");
                });

            modelBuilder.Entity("RealEstateProject.Models.Owner", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("RealEstateProject.Models.Property", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MediaFiles");

                    b.Navigation("Promotions");

                    b.Navigation("PropertyApprovals");
                });

            modelBuilder.Entity("RealEstateProject.Models.ServicePartner", b =>
                {
                    b.Navigation("Service_Requests");
                });

            modelBuilder.Entity("RealEstateProject.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("RealEstateProject.Models.Tenant", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Bookings");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("RealEstateProject.Models.User", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("Tenant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
